### ISSUE TITLE
[Feature Request] .deb package for Debian and Ubuntu

### ISSUE THREAD

**Issue by aaronfranke** [Airblader/unclutter-xfixes#21]
I would love for there to be an easy to install .deb package. It would make things easier. I know how to compile but if I want to show others this tool then it's much easier to send them a .deb package.

**Comment by Airblader** [comment]
Yes, I fully agree. But that's a job for Debian, not me. I cannot possibly maintain packages for all distros that I don't even use myself. :-) I'm just upstream. 

Feel free to create the package or ping Debian maintainers to create one. 

FYI: there was discussion in Debian to actually replace the old unclutter with my version, but this can't happen yet because it's not fully compatible. 

Closing since there's nothing for me to do. But please do let me know when the package has been created!
