### ISSUE TITLE
make of release tarball cannot set proper version

### ISSUE THREAD

**Issue by maximbaz** [Airblader/unclutter-xfixes#33]
Hey, found your tool via https://github.com/i3/i3/issues/3506 and want to package it for Arch Linux, eventually in `[community]`. I noticed that when I run `make all` on the release tarball, I get these errors:

```
==> Starting build()...
rm -f unclutter obj/extensions.o obj/unclutter.o obj/cursor.o obj/event.o obj/util.o
make: git: Command not found
rm -f man/*.1 man/*.xml
make: git: Command not found
gcc -D_FORTIFY_SOURCE=2 -D'__VERSION=""' "-Iinclude" -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -std=gnu99 -Wall -Wundef -Wshadow -Wformat-security -o "obj/extensions.o" -c "src/extensions.c"
make: git: Command not found
make: git: Command not found
...
```

But even if I add `git` to `makedepends`, I get this:

```
rm -f unclutter obj/extensions.o obj/unclutter.o obj/cursor.o obj/event.o obj/util.o
fatal: not a git repository (or any of the parent directories): .git
rm -f man/*.1 man/*.xml
fatal: not a git repository (or any of the parent directories): .git
gcc -D_FORTIFY_SOURCE=2 -D'__VERSION=""' "-Iinclude" -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -std=gnu99 -Wall -Wundef -Wshadow -Wformat-security -o "obj/extensions.o" -c "src/extensions.c"
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
...
```

Ideally I'd run it as `make version=1.3 all` or `VERSION=1.3 make all` to be able to set the version, but I think it won't be possible today.

Agree? Could you adapt the Makefile please? 🙂

**Comment by Airblader** [comment]
Hi,

thanks for opening this issue. There is actually already unclutter-xfixes-git in the AUR, though I'd definitely not be against moving this to community if you're a TU and would like to do so.

I think it's better if the version baked into the executable is defined in unclutter-xfixes itself rather than the packaging process. There's no real need to have a commit-specific version in the Makefile anyway, so I'm thinking of just doing it as done in #34. Would that work for you?

**Comment by maximbaz** [comment]
I did use the -git version already, it seems quite popular and solves real issue, so I think worth being in community. 

If you don't mind changing version in code all the time, it's fine by me, I suggested this because setting version in PKGBUILD via $pkgver is easy

**Comment by Airblader** [comment]
Yeah, I'd have to adapt the file whenever I release, but that's fine (and happens very rarely). I just think the version should be defined by the tool, not the package, otherwise the same software has different versions on different distros. :-)

I've merged and released it as https://github.com/Airblader/unclutter-xfixes/releases/tag/v1.4

**Comment by Airblader** [comment]
… and then we can close this, I guess. Thank you!

**Comment by maximbaz** [comment]
Agreed, thank you! I tested and `v1.4` build well now 😉 

I'm currently anyway waiting for my PGP key to be signed before I can push packages to `[community]`, so for now I [published it on AUR](https://aur.archlinux.org/packages/unclutter-xfixes/) and I'll move it later.

Please add this package to `conflicts` array of `unclutter-xfixes-git` on AUR. 

And finally thanks for your fast response and fix!

**Comment by Airblader** [comment]
Thank you for packaging this! I've updated the -git package now.

**Comment by maximbaz** [comment]
Hey @Airblader, we talked internally and decided to ship `unclutter-xfixes` instead of the legacy `unclutter`. Congratulations, `community/unclutter` is now based on this repo 😉

**Comment by Airblader** [comment]
@maximbaz That's awesome news, thank you!
