### ISSUE TITLE
asciidoc needed?

### ISSUE THREAD

**Issue by lupin3rd** [Airblader/unclutter-xfixes#5]
I try to compile unclutter-xfixes on my debian 8 and installed some libs needed, now i have:
make: a2x: Command not found
Seem necessary to install asciidoc package to compile fine... but i must install 750MB of packages :-)
Is really necessary this?
Thank you

**Comment by Airblader** [comment]
It's necessary if you want a man page. If you can live without it, just uncomment the appropriate lines in the Makefile and go ahead. 

It'd of course be great to get this into the Debian repositories. That way the man page can be precompiled and the dependency would not be necessary. Since I don't run Debian, I can't do that, though.

**Comment by Airblader** [comment]
Alternatively, install asciidoc, install unclutter-xfixes and then remove asciidoc again.

**Comment by Airblader** [comment]
(I'm going to close the issue, I think I've said everything above. There's two workarounds and the proper way is someone providing a proper package for Debian)

**Comment by lupin3rd** [comment]
thank you!

**Comment by Airblader** [comment]
If someone does happen to provide a Debian package, I'd love to know so I can put it in the README.
