### ISSUE TITLE
Question regarding XFixesHideCursor

### ISSUE THREAD

**Issue by beaumanvienna** [Airblader/unclutter-xfixes#60]
Is it okay if I ask a question regarding XFixesHideCursor here? I figured you guys are the experts on this subject..

I wrote [this function](https://github.com/beaumanvienna/marley/blob/7785dcbf27fe585c31991cb1d371e767af6638d3/src/gui.cpp#L92) to hide the mouse pointer. It works when I call it with `hide_or_show_cursor_X11(true)`. The pointer disappears entirely. However, the cursor won't come back on when I call it  with `hide_or_show_cursor_X11(false)`. Any idea what I am doing wrong?

Thanks a lot!

**Comment by Airblader** [comment]
(Closing since not an issue of unclutter-xfixes)

If you're trying to show the cursor which has been hidden by you (same client), I think it should work, so not much else I can say, sorry. You could definitely try asking on SO or the X mailing list, though. I unfortunately don't have time to dig into your code deeper at the moment.
